### ISSUE TITLE
v1.0 - make init errors

### ISSUE THREAD

**Issue by kolaps** [68publishers/consent-management-platform#66]
After exec - make init got errors:
1. error /var/www/html/vendor does not exist and could not be created.
```
docker exec -it cmp-app composer install --no-interaction --no-ansi --prefer-dist --no-progress --optimize-autoloader
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 167 installs, 0 updates, 0 removals

In Filesystem.php line 254:

  /var/www/html/vendor does not exist and could not be created.
```
to resolve issue create folder **vendor**
```mkdir vendor
chmod 777 vendor```

2. yarn error
```error Could not write file "/var/www/html/yarn-error.log": "EACCES: permission denied, open '/var/www/html/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/var/www/html/node_modules'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
to resolve issue create folder **node_modules**
```mkdir node_modules
chmod 777 node_modules```

3. yarn error
```yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ /var/www/html/node_modules/.bin/encore prod
Running webpack ...

  Error: EACCES: permission denied, mkdir '/var/www/html/public/dist'
```
to resolve issue create folder **dist**
```mkdir public/dist
chmod 777 public/dist```

4. nette cache error
```make[2]: Leaving directory '/root/cmp'
# Duplicity with init
make data-migration
make[2]: Entering directory '/root/cmp'
docker exec -it cmp-app bin/console migrations:migrate --no-interaction
Nette\IOException: Unable to create directory '/var/www/html/var/cache' with mode 777. Permission denied in /var/www/html/vendor/nette/utils/src/Utils/FileSystem.php:29
Stack trace:
#0 /var/www/html/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(351): Nette\Utils\FileSystem::createDir('/var/www/html/s...')
#1 /var/www/html/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(278): Nette\Bootstrap\Configurator->getCacheDirectory()
```

also missing var/log & var/cache folder..
Have created missing folders & chmod 777..

Now is working https://prnt.sc/TN7rF-12-33c

**Comment by tg666** [comment]
Hi
The problem shouldn't be that some folders are missing (they are created automatically when needed), but rather the permissions.
What system were you running this on (Mac OS, Linux, Win)?

**Comment by rainje** [comment]
I have the same issue, running fresh debian 12.

Running as a user or with sudo gives the same result.

**Comment by rainje** [comment]
@kolaps Could you share your modified files? I guess the Makefile. Cheers.
